
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'D5B268CAE86B8C34A6CF77C5D8821EDD'
    
_lr_action_items = {'AND':([2,5,6,12,13,14,15,16,17,18,],[7,-2,7,7,-3,7,7,7,7,7,]),'XOR':([2,5,6,12,13,14,15,16,17,18,],[8,-2,8,8,-3,8,8,8,8,8,]),')':([5,6,12,13,14,15,16,17,18,],[-2,13,-4,-3,-5,-7,-8,-6,-9,]),'(':([0,1,4,7,8,9,10,11,],[1,1,1,1,1,1,1,1,]),'NAND':([2,5,6,12,13,14,15,16,17,18,],[9,-2,9,9,-3,9,9,9,9,9,]),'NOT':([0,1,4,7,8,9,10,11,],[4,4,4,4,4,4,4,4,]),'BIT':([0,1,4,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'OR':([2,5,6,12,13,14,15,16,17,18,],[10,-2,10,10,-3,10,10,10,10,10,]),'NOR':([2,5,6,12,13,14,15,16,17,18,],[11,-2,11,11,-3,11,11,11,11,11,]),'$end':([2,3,5,12,13,14,15,16,17,18,],[-1,0,-2,-4,-3,-5,-7,-8,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'argument':([0,1,4,7,8,9,10,11,],[2,6,12,14,15,16,17,18,]),'statement':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> argument','statement',1,'p_statement','Bit_Parser.py',30),
  ('argument -> BIT','argument',1,'p_argument_bit','Bit_Parser.py',34),
  ('argument -> ( argument )','argument',3,'p_argument_paren','Bit_Parser.py',38),
  ('argument -> NOT argument','argument',2,'p_argument_not','Bit_Parser.py',42),
  ('argument -> argument AND argument','argument',3,'p_argument_operate','Bit_Parser.py',46),
  ('argument -> argument OR argument','argument',3,'p_argument_operate','Bit_Parser.py',47),
  ('argument -> argument XOR argument','argument',3,'p_argument_operate','Bit_Parser.py',48),
  ('argument -> argument NAND argument','argument',3,'p_argument_operate','Bit_Parser.py',49),
  ('argument -> argument NOR argument','argument',3,'p_argument_operate','Bit_Parser.py',50),
]
